
import { Inter } from 'next/font/google'
import './globals.css'
import { StateContextProvider } from '../context/contextapi'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}) {
  return (
    <html lang="en">
     <body className={`${inter.className} w-[100vw] h-[100vh] bg-black bg-gradient-texture`}>
      <StateContextProvider>

        {children}

        </StateContextProvider>
        </body>
    </html>
  )
}
